name: Docker Image CI

on:
  push:
    branches: [ "master", "Ahmed" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t shell .

    - name: Run the unit tests
      run: docker run -p 80:8000 -ti --rm shell /comp0010/tools/test

    - name: Build the system tests 
      run: docker build -t comp0010-system-test .

    - name: Run the system tests
      run: python system_test/tests.py -v
