name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t shell .
    
    - name: Run coverage tests
      run: docker run --rm shell /comp0010/tools/coverage --value   

    - name: Run static analysis test
      run: docker run --rm shell /comp0010/tools/analysis_flake8      

    - name: Run the unit tests
      run: docker run --rm shell /comp0010/tools/test_nose2                                        

    - name: Build the system tests 
      run: docker build -t comp0010-system-test .

    - name: Run the system tests
      run: python system_test/tests.py -v
    
